ZavodTask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("newsBlog.urls", 'newsBlog'), namespace='newsBlog')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsBlog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'newsBlog'
urlpatterns = [
        path('', views.view, name='news'),
        path('<slug>', views.post, name='post'),
        path('tag/<int:tag_id>', views.tag, name='tag'),
        path('viewsCount/', views.viewsCount, name='listWithViews'),
]

newsBlog/models.py
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    TagName = models.CharField(max_length=65)
    id = models.BigAutoField(primary_key=True)
    def __str__(self):
        return self.TagName

    def get_absolute_url(self):
        return reverse('newsBlog:tag', args=[self.id])


# Модель, внутри которой хранятся ip посетителей
class IP(models.Model):
    IpName = models.CharField(max_length=45)


class News(models.Model):
    header = models.CharField(max_length=165, db_index=True, unique=True)
    slug = models.SlugField(max_length=165, unique=True)
    body = models.TextField()
    image = models.ImageField(upload_to='images/%Y/%m/%d', blank=True)
    tags = models.ManyToManyField('Tag', blank=False, related_name='tags')
    views = models.ManyToManyField(IP, blank=True)

    def __str__(self):
        return self.header

    def get_absolute_url(self):
        return reverse('newsBlog:post',
                       args=[self.slug])

    # функция подсчета просмотров через поле views
    def total_views(self):
        return self.views.count()

newsBlog/views.py
from django.shortcuts import render, get_object_or_404
from .models import News, IP, Tag


# функция получения ip пользователя, возможно стоило сделать декоратором
def get_ip(request):
    http_x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if http_x_forwarded_for:
        ip = http_x_forwarded_for.split(',')[0]  # сплит для получения только айпи, без прокси
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def view(request):
    news = News.objects.all()
    return render(request, 'main.html', {'news': news})


def post(request, slug):
    exact_post = get_object_or_404(News, slug=slug)
    ip = get_ip(request)
    if IP.objects.filter(IpName=ip).exists():
        exact_post.views.add(IP.objects.get(IpName=ip))
    else:
        IP.objects.create(IpName=ip)
        exact_post.views.add(IP.objects.get(IpName=ip))
    return render(request, 'post.html', {'exact_post': exact_post})


def tag(request, tag_id):
    news_objects = News.objects.filter(tags__id=tag_id)
    current_tag = Tag.objects.get(id=tag_id)
    return render(request, 'tags.html', {'news_obj': news_objects, 'curr_tag': current_tag})


def viewsCount(request):
    news = News.objects.all()
    for n in News.objects.all():
        n.total_views()
    return render(request, 'listWithViews.html', {'news': news})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block head %}
    {% endblock head %}
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'newsBlog:news' %}">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'newsBlog:listWithViews' %}">Статистика просмотров</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock content %}
</body>
</html>

templates/listWithViews.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Статистка просмотров
{% endblock title %}
{% block content %}

{% for post in news %}

    <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.header }}</a> Просмотрело: {{ post.total_views }}</h5>
        <p class="card-text">{{ post.body|truncatechars:75}}</p>
      </div>
    </div>
  </div>
</div>
{%endfor %}
{% endblock content %}

templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Главная страница новостного блога
{% endblock title %}
{% block content %}

{% for post in news %}

    <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{% if post.image %}{{ post.image.url }}{% endif %}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.header }}</a></h5>
        <p class="card-text">{{ post.body|truncatechars:75}}</p>
      </div>
    </div>
  </div>
</div>
{%endfor %}
{% endblock content %}

templates/post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ exact_post.header }}
{% endblock title %}
{% block content %}
    <div style="width: 60vw; margin-left: 25vw; border: 1px solid grey; height: max-content">
<img src="{% if exact_post.image %}{{ exact_post.image.url }}{% endif %}" style="margin-left: 22vw;width: 300px; height: 300px">
<h1 style="text-align: center">{{ exact_post.header }}</h1>
    <p>{{ exact_post.body }}</p>
    <span>Теги:</span>
{% for tags in exact_post.tags.all %}
    <a href="{{ tags.get_absolute_url }}">{{ tags }}</a>
    {% endfor%}
   <p> Просмотров :  {{ exact_post.total_views }}</p>
</div>
{% endblock content %}

templates/tags.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ curr_tag }}
{% endblock title %}
{% block content %}
    <h1>Новостные посты по тегу {{ curr_tag }} </h1>
    {% for post in news_obj %}
    <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{% if post.image %}{{ post.image.url }}{% endif %}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.header }}</a></h5>
        <p class="card-text">{{ post.body|truncatechars:75}}</p>
      </div>
    </div>
  </div>
</div>
    {% endfor %}
{% endblock content %}